-- CreateTable
CREATE TABLE "Warning" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" STRING NOT NULL,
    "guild_id" STRING NOT NULL,

    CONSTRAINT "Warning_pkey" PRIMARY KEY ("id")
);
